name: "Build and Push Docker Image with version"

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Define Image Date Tag
        id: vars
        run: |
          export TZ=America/Toronto
          DATE_TAG=$(date +'%Y%m%d-%H%M')
          IMAGE_NAME="expense-mgmt-auth-ms01"
          echo "DATE_TAG=${DATE_TAG}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Debug - List files in build context
        run: |
          ls -la /app/

      - name: Build Docker Image (No Cache)
        run: |
          docker build --no-cache -t ${IMAGE_NAME}:latest -t ${IMAGE_NAME}:${DATE_TAG} .

      - name: Push Docker Images
        run: |
          docker push ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:${DATE_TAG}
